global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "task-manager"
    metrics_path: "/actuator/prometheus"
    scheme: "http"
    basic_auth:
      username: "actuator"
      password: "actuator"
    static_configs:
      - targets: ["host.docker.internal:8082"]